-- Seed: the group's real game of Aug 19 2026.
--
-- Generated by scripts/gen-seed.mjs from lib/scoring/fixtures/aug-19-2026.ts, the
-- same fixture the engine tests assert against. Do not edit by hand; regenerate.
--
-- Final scores this must produce: Player A -23, Player B -39, Player C +64, Player D -2.
--
-- Usage: this seeds the game against one account. Either set the email for the
-- run, which keeps it out of version control:
--
--   set app.seed_owner_email = 'you@example.com';
--   \i supabase/seed.sql
--
-- or replace the fallback below before running it.

do $$
declare
  v_owner uuid;
  v_game uuid;
  v_owner_email text := coalesce(
    nullif(current_setting('app.seed_owner_email', true), ''),
    'you@example.com'
  );
begin
  select id into v_owner from auth.users where email = v_owner_email;

  if v_owner is null then
    raise notice 'No account found for %, skipping seed. Sign in once, then rerun.', v_owner_email;
    return;
  end if;

  -- Idempotent: drop any previous copy of this seeded game first.
  delete from public.games
   where owner_id = v_owner and date = date '2026-08-19' and share_slug = 'aug19-2026';

  insert into public.games (owner_id, date, player_names, zaa_wu_penalty, share_slug)
  values (
    v_owner,
    date '2026-08-19',
    array['Player A', 'Player B', 'Player C', 'Player D'],
    13,
    'aug19-2026'
  )
  returning id into v_game;

  insert into public.hands (game_id, seq, type, winner_seat, discarder_seat, offender_seat, points)
  -- In a multi row VALUES list the literals resolve to text, so the enum and
  -- the smallint seats need explicit casts on the way in.
  select
    v_game,
    seq,
    type::public.hand_type,
    winner_seat::smallint,
    discarder_seat::smallint,
    offender_seat::smallint,
    points
  from (values
    (0, 'zi_mo', 0, null, null, 3),
    (1, 'zi_mo', 3, null, null, 6),
    (2, 'ceot_cung', 2, 1, null, 3),
    (3, 'ceot_cung', 2, 3, null, 3),
    (4, 'ceot_cung', 3, 1, null, 5),
    (5, 'ceot_cung', 2, 0, null, 6),
    (6, 'ceot_cung', 1, 0, null, 4),
    (7, 'ceot_cung', 3, 2, null, 3),
    (8, 'ceot_cung', 1, 2, null, 5),
    (9, 'zi_mo', 2, null, null, 3),
    (10, 'ceot_cung', 3, 2, null, 3),
    (11, 'zi_mo', 2, null, null, 4),
    (12, 'zi_mo', 2, null, null, 5),
    (13, 'zi_mo', 1, null, null, 6),
    (14, 'zi_mo', 2, null, null, 5),
    (15, 'ceot_cung', 3, 1, null, 3),
    (16, 'zi_mo', 0, null, null, 5),
    (17, 'ceot_cung', 0, 1, null, 4),
    (18, 'ceot_cung', 0, 2, null, 4)
  ) as h(seq, type, winner_seat, discarder_seat, offender_seat, points);

  raise notice 'Seeded game % with % hands', v_game, (select count(*) from public.hands where game_id = v_game);
end $$;
