/*
 * Generate supabase/seed.sql from the same fixture the engine tests use, so the
 * seeded game can never drift from the reference game.
 *
 *   node scripts/gen-seed.mjs > supabase/seed.sql
 */
import { readFileSync, writeFileSync } from 'node:fs';

const source = readFileSync(new URL('../lib/scoring/fixtures/aug-19-2026.ts', import.meta.url), 'utf8');

// Pull the compact rows straight out of the fixture file.
const rawBlock = source.slice(source.indexOf('const RAW = ['), source.indexOf('] as const;'));
const rows = [...rawBlock.matchAll(/\{\s*t:\s*'([ds])',\s*w:\s*(\d)(?:,\s*f:\s*(\d))?,\s*p:\s*(\d+)\s*\}/g)].map(
  ([, t, w, f, p]) => ({ t, w: Number(w), f: f === undefined ? null : Number(f), p: Number(p) }),
);

if (rows.length !== 19) {
  throw new Error(`Expected 19 hands in the fixture, parsed ${rows.length}`);
}

const values = rows
  .map((row, index) => {
    const type = row.t === 's' ? 'zi_mo' : 'ceot_cung';
    const discarder = row.f === null ? 'null' : row.f;
    return `    (${index}, '${type}', ${row.w}, ${discarder}, null, ${row.p})`;
  })
  .join(',\n');

const sql = `-- Seed: the group's real game of Aug 19 2026.
--
-- Generated by scripts/gen-seed.mjs from lib/scoring/fixtures/aug-19-2026.ts, the
-- same fixture the engine tests assert against. Do not edit by hand; regenerate.
--
-- Final scores this must produce: Player A -23, Player B -39, Player C +64, Player D -2.
--
-- Usage: this seeds the game against one account. Either set the email for the
-- run, which keeps it out of version control:
--
--   set app.seed_owner_email = 'you@example.com';
--   \\i supabase/seed.sql
--
-- or replace the fallback below before running it.

do $$
declare
  v_owner uuid;
  v_game uuid;
  v_owner_email text := coalesce(
    nullif(current_setting('app.seed_owner_email', true), ''),
    'you@example.com'
  );
begin
  select id into v_owner from auth.users where email = v_owner_email;

  if v_owner is null then
    raise notice 'No account found for %, skipping seed. Sign in once, then rerun.', v_owner_email;
    return;
  end if;

  -- Idempotent: drop any previous copy of this seeded game first.
  delete from public.games
   where owner_id = v_owner and date = date '2026-08-19' and share_slug = 'aug19-2026';

  insert into public.games (owner_id, date, player_names, rules, rule_set_name, share_slug)
  values (
    v_owner,
    date '2026-08-19',
    array['Player A', 'Player B', 'Player C', 'Player D'],
    -- The group's own table: linear curve, 3 to 13 faan. These are the rules
    -- the reference scores were produced under.
    jsonb_build_object(
      'preset', 'our_table',
      'minFaan', 3,
      'faanCap', 13,
      'limitPaysCap', true,
      'curve', 'linear',
      'selfDrawEachMult', 2,
      'discardShooterMult', 2,
      'discardOthersMult', 1,
      'dealerMult', 1,
      'selfDrawBonusFaan', 0,
      'zaaWuPenalty', 13,
      'newSix', false,
      'sevenPairs', false,
      'baseUnit', 0,
      'currency', '$'
    ),
    'Our table',
    'aug19-2026'
  )
  returning id into v_game;

  insert into public.hands (game_id, seq, type, winner_seat, discarder_seat, offender_seat, faan)
  -- In a multi row VALUES list the literals resolve to text, so the enum and
  -- the smallint seats need explicit casts on the way in.
  select
    v_game,
    seq,
    type::public.hand_type,
    winner_seat::smallint,
    discarder_seat::smallint,
    offender_seat::smallint,
    faan
  from (values
${values}
  ) as h(seq, type, winner_seat, discarder_seat, offender_seat, faan);

  raise notice 'Seeded game % with % hands', v_game, (select count(*) from public.hands where game_id = v_game);
end $$;
`;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`seed.sql written with ${rows.length} hands`);
